PTL-1200 add details of not null to tables basics
genesiscommunitysuccess/docs pull request #1526
Opened 2024-03-01 09:43 UTC by wjhendry

also copies yesterday's Ray Chee update to Previous

Thank you for contributing to the documentation.

Do the changes you have made apply to both Current and Previous versions?
Y

Have you checked all new or changed links?
Y

Is there anything else you would like us to know?
N

For reference: 

  - We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb245f246ff872789035451a0c4)
  - We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04ec6fe12f4262b90d192effd8059b) 

**This week's exciting excerpts from the style guide**

- We write in UK English, with Oxford English Dictionary (OED) spellings, grammar and vocabulary.  

Use the present tense wherever possible. Only use another tense where it is strictly necessary.

- Present tense (preferred whenever possible): *The script creates a new folder.*
- Future tense (avoid whenever possible): *The script will create a new folder.*

2024-03-01 10:11 UTC, GuiWar requested changes
Hi John. There are some changes that needs to be addressed here. Happy to huddle to sort this out.

2024-03-01 10:11 UTC, GuiWar commented on versioned_docs/version-previous/02_database/01_fields-tables-views/01_fields/01_fields-basics.md
>  | Parameter | Default value | Sample Usage | Value Type | Description |
Name field is missing. and I believe name and type are mandatory.

2024-03-01 10:11 UTC, GuiWar commented on versioned_docs/version-previous/02_database/01_fields-tables-views/01_fields/01_fields-basics.md
>  | default | null | `field(name = "AGE", type = INT, default=20)` | The same type as the field | Set a default value for the field where not supplied on a database insert. Mandatory for `ENUM` |
default is mandatory for ENUM inside the ENUM declaration. For example: field(name="COUNTRY", type=ENUM("BRAZIL", "KUWAIT","BHUTAN",default="BRAZIL")

2024-03-01 10:11 UTC, GuiWar commented on versioned_docs/version-previous/02_database/01_fields-tables-views/01_fields/01_fields-basics.md
> +| nullable | true | `field(name = "DESCRIPTION", type = STRING, nullable=false)`; see below | boolean | false if the field is not nullable  |
This argument is not available if type = ENUM

2024-03-01 11:03 UTC, wjhendry commented
> Hi John. There are some changes that needs to be addressed here. Happy to huddle to sort this out.

Should all be there now

2024-03-01 11:22 UTC, dbarros1979 approved these changes

2024-03-05 10:07 UTC, GuiWar approved these changes

2024-03-05 10:51 UTC, merged